# Generated by Django 3.2.11 on 2022-01-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('quantity', models.IntegerField(default=0)),
                ('origin_country', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('deletion_comment', models.CharField(blank=True, max_length=50, null=True)),
                ('deletion_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
