# Generated by Django 3.2.7 on 2022-01-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='uid',
            new_name='uuid',
        ),
    ]
