# Generated by Django 3.2.11 on 2022-01-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220109_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
